[package]
name = "veda-nano-bpmn"
version = "0.1.0"
authors = ["Itiua <ValeriyBushenev@gmail.com>"]
edition = "2018"


[dependencies]
log = "0.4"
quick-xml = {version = "0.18.1", features = [ "serialize" ]}
maplit = "1.0.2"
rusty_v8 = "0.14.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
indextree = "4.2.0"
nanoid = "0.3.0"

v_queue = "0.1"

v_api = { git = "https://github.com/semantic-machines/v-common-api.git", branch = "main" }
v_onto = { git = "https://github.com/semantic-machines/v-common-onto.git" }
v_v8 = { git = "https://github.com/semantic-machines/v-common-v8.git" }
v_module = { git = "https://github.com/semantic-machines/v-common-module.git" }
v_storage = { git = "https://github.com/semantic-machines/v-common-storage.git" }
